// PBLA (Philadelphia Box Lacrosse Association) hardcoded data
// Source: https://secure.sportability.com/spx/Leagues/ (LgID=50731 for 2026, LgID=50247 for 2025)

// Types are the single source of truth in @pll/shared
export type {
  PblaTeam,
  PblaPlayer,
  PblaGoalie,
  PblaRosterEntry,
  PblaGame,
  PblaSeason,
  PblaTeamPalette,
} from '@pll/shared';

import type { PblaTeam, PblaPlayer, PblaGoalie, PblaRosterEntry, PblaGame, PblaSeason, PblaTeamPalette } from '@pll/shared';

const TEAM_COLORS: Record<string, string> = {
  'More Dudes LC': '#800000',
  'More Dudes': '#800000',
  Outlaws: '#003087',
  Edge: '#ef4444',
  'The Edge': '#ef4444',
  Thunder: '#facc15',
  'Pups LC': '#ff6600',
  'Beer Wolves': '#22c55e',
  Revolution: '#3b82f6',
  'Revolution LC': '#3b82f6',
  'Black Storm': '#64748b',
};

export type TeamPalette = PblaTeamPalette;

const TEAM_PALETTES: Record<string, TeamPalette> = {
  'More Dudes LC': { primary: '#800000', secondary: '#d2b48c', accent: '#ffffff' },
  'More Dudes': { primary: '#800000', secondary: '#d2b48c', accent: '#ffffff' },
  Outlaws: { primary: '#003087', secondary: '#111111', accent: '#ffffff' },
  Edge: { primary: '#111111', secondary: '#ef4444', accent: '#facc15' },
  'The Edge': { primary: '#111111', secondary: '#ef4444', accent: '#facc15' },
  Thunder: { primary: '#111111', secondary: '#facc15', accent: '#800000' },
  'Pups LC': { primary: '#ff6600', secondary: '#111111', accent: '#ff6600' },
  'Beer Wolves': { primary: '#22c55e', secondary: '#f97316', accent: '#111111' },
  Revolution: { primary: '#3b82f6', secondary: '#ffffff', accent: '#111111' },
  'Revolution LC': { primary: '#3b82f6', secondary: '#ffffff', accent: '#111111' },
  'Black Storm': { primary: '#64748b', secondary: '#111111', accent: '#94a3b8' },
};

export function teamColor(name: string): string {
  return TEAM_COLORS[name] ?? '#6b7280';
}

export function teamPalette(name: string): TeamPalette {
  return TEAM_PALETTES[name] ?? { primary: '#6b7280', secondary: '#374151', accent: '#9ca3af' };
}

export function teamSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

/** Find a team across all seasons by slug */
export function findTeamBySlug(slug: string): { team: PblaTeam; season: PblaSeason } | null {
  for (const season of SEASONS) {
    const team = season.teams.find((t) => teamSlug(t.name) === slug);
    if (team) return { team, season };
  }
  return null;
}

/** Get all players for a team in a given season */
export function getTeamPlayers(teamName: string, season: PblaSeason): PblaPlayer[] {
  return season.players.filter((p) => p.team === teamName);
}

/** Get all goalies for a team in a given season */
export function getTeamGoalies(teamName: string, season: PblaSeason): PblaGoalie[] {
  return season.goalies.filter((g) => g.team === teamName);
}

/** Get the full roster for a team in a given season */
export function getTeamRoster(teamName: string, season: PblaSeason): PblaRosterEntry[] {
  return season.rosters[teamName] ?? [];
}

export const SEASONS: PblaSeason[] = [
  {
    year: 2026,
    leagueId: 50731,
    label: '2026 (Current)',
    teams: [
      { id: 343516, name: 'Thunder', gp: 10, wins: 10, losses: 0, ties: 0, otw: 0, otl: 0, pts: 30, pf: 118, pa: 67, diff: 51, streak: 'W10', color: '#facc15', captain: 'Jim Glielmi', jerseyImg: '/logos/pbla-thunder.png' },
      { id: 343514, name: 'Pups LC', gp: 10, wins: 6, losses: 4, ties: 0, otw: 0, otl: 0, pts: 18, pf: 96, pa: 80, diff: 16, streak: 'L3', color: '#ff6600', captain: 'Andrew Sloan', jerseyImg: 'https://img1.wsimg.com/isteam/ip/9e5f3063-7bf9-40d1-b593-5c59c6903080/Pups.png/:/rs=w:600,cg:true,m' },
      { id: 343517, name: 'More Dudes LC', gp: 10, wins: 8, losses: 2, ties: 0, otw: 0, otl: 0, pts: 24, pf: 124, pa: 62, diff: 62, streak: 'W5', color: '#800000', captain: 'Murf Butler', jerseyImg: '/logos/pbla-moredudes.png' },
      { id: 343511, name: 'Outlaws', gp: 10, wins: 5, losses: 5, ties: 0, otw: 0, otl: 0, pts: 15, pf: 97, pa: 90, diff: 7, streak: 'W1', color: '#003087', captain: 'Joe Stainer', jerseyImg: '/logos/pbla-outlaws.png' },
      { id: 343512, name: 'Edge', gp: 11, wins: 2, losses: 9, ties: 0, otw: 0, otl: 0, pts: 6, pf: 71, pa: 130, diff: -59, streak: 'L4', color: '#ef4444', captain: 'Matt O\'Brian', jerseyImg: '/logos/pbla-edge.png' },
      { id: 343515, name: 'Revolution', gp: 10, wins: 2, losses: 8, ties: 0, otw: 0, otl: 0, pts: 6, pf: 59, pa: 100, diff: -41, streak: 'W1', color: '#3b82f6', captain: 'Bill Kennedy', jerseyImg: '/logos/pbla-revolution.png' },
      { id: 343513, name: 'Beer Wolves', gp: 9, wins: 2, losses: 7, ties: 0, otw: 0, otl: 0, pts: 6, pf: 64, pa: 100, diff: -36, streak: 'L1', color: '#22c55e', captain: 'Ryan Mackey', jerseyImg: 'https://img1.wsimg.com/isteam/ip/9e5f3063-7bf9-40d1-b593-5c59c6903080/BeerWolves.png/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true' },
    ],
    players: [
      { jersey: 7, name: 'Nick Fox', team: 'Pups LC', gp: 9, goals: 24, assists: 8, points: 32, penalties: 11, pim: 22 },
      { jersey: 10, name: 'Austin Conner', team: 'Thunder', gp: 9, goals: 21, assists: 6, points: 27, penalties: 2, pim: 7 },
      { jersey: 67, name: 'Erik Ojert', team: 'More Dudes LC', gp: 7, goals: 10, assists: 17, points: 27, penalties: 0, pim: 0 },
      { jersey: 3, name: 'Ethan Krauss', team: 'More Dudes LC', gp: 8, goals: 19, assists: 7, points: 26, penalties: 4, pim: 8 },
      { jersey: 9, name: 'Luke Mingioni', team: 'Beer Wolves', gp: 8, goals: 19, assists: 5, points: 24, penalties: 4, pim: 8 },
      { jersey: 55, name: 'Dalton Hofmann', team: 'More Dudes LC', gp: 7, goals: 19, assists: 4, points: 23, penalties: 1, pim: 2 },
      { jersey: 24, name: 'James Lindsay', team: 'Pups LC', gp: 9, goals: 16, assists: 5, points: 21, penalties: 1, pim: 2 },
      { jersey: 51, name: 'Caiden Zadell', team: 'Pups LC', gp: 7, goals: 10, assists: 11, points: 21, penalties: 4, pim: 8 },
      { jersey: 96, name: 'George Downey', team: 'Outlaws', gp: 10, goals: 17, assists: 2, points: 19, penalties: 1, pim: 2 },
      { jersey: 5, name: 'Jonathan Miller', team: 'More Dudes LC', gp: 7, goals: 14, assists: 5, points: 19, penalties: 9, pim: 18 },
      { jersey: 33, name: 'Patrick Resch', team: 'Thunder', gp: 10, goals: 14, assists: 5, points: 19, penalties: 3, pim: 6 },
      { jersey: 92, name: 'Brian Beatson', team: 'Outlaws', gp: 7, goals: 13, assists: 6, points: 19, penalties: 1, pim: 2 },
      { jersey: 53, name: 'Mackenzie Ensley', team: 'Beer Wolves', gp: 8, goals: 12, assists: 7, points: 19, penalties: 0, pim: 0 },
      { jersey: 55, name: 'Philip Melecio', team: 'Outlaws', gp: 9, goals: 13, assists: 5, points: 18, penalties: 1, pim: 2 },
      { jersey: 51, name: 'Kyle Marr', team: 'Thunder', gp: 6, goals: 10, assists: 8, points: 18, penalties: 0, pim: 0 },
      { jersey: 1, name: 'Jake Hervada', team: 'Thunder', gp: 9, goals: 7, assists: 11, points: 18, penalties: 2, pim: 4 },
      { jersey: 76, name: 'Nate Winters', team: 'Beer Wolves', gp: 8, goals: 15, assists: 2, points: 17, penalties: 1, pim: 2 },
      { jersey: 51, name: 'Julian Definis', team: 'Edge', gp: 8, goals: 12, assists: 5, points: 17, penalties: 1, pim: 2 },
      { jersey: 2, name: 'Connor Freer', team: 'Revolution', gp: 8, goals: 11, assists: 4, points: 15, penalties: 2, pim: 4 },
      { jersey: 17, name: 'Murph Butler', team: 'More Dudes LC', gp: 7, goals: 11, assists: 4, points: 15, penalties: 1, pim: 2 },
      { jersey: 88, name: 'Brian Sullivan', team: 'Outlaws', gp: 8, goals: 6, assists: 9, points: 15, penalties: 0, pim: 0 },
      { jersey: 16, name: 'Dylan Portnoy', team: 'Outlaws', gp: 8, goals: 12, assists: 2, points: 14, penalties: 1, pim: 0 },
      { jersey: 77, name: 'Soloman Hess', team: 'Pups LC', gp: 6, goals: 12, assists: 2, points: 14, penalties: 1, pim: 2 },
      { jersey: 4, name: 'Jack Glemser', team: 'Edge', gp: 6, goals: 10, assists: 4, points: 14, penalties: 0, pim: 0 },
      { jersey: 91, name: 'Matt Klinges', team: 'Thunder', gp: 8, goals: 10, assists: 4, points: 14, penalties: 0, pim: 0 },
      { jersey: 4, name: 'Joey Klinges', team: 'Thunder', gp: 6, goals: 6, assists: 8, points: 14, penalties: 1, pim: 2 },
      { jersey: 99, name: 'Adam Goldner', team: 'Thunder', gp: 7, goals: 9, assists: 3, points: 12, penalties: 2, pim: 4 },
      { jersey: 5, name: 'Curtis Reinard', team: 'Edge', gp: 6, goals: 9, assists: 3, points: 12, penalties: 0, pim: 0 },
      { jersey: 39, name: 'Richard Nelson', team: 'Edge', gp: 6, goals: 9, assists: 3, points: 12, penalties: 0, pim: 0 },
      { jersey: 9, name: 'Nicholas Cost', team: 'Revolution', gp: 6, goals: 8, assists: 4, points: 12, penalties: 0, pim: 0 },
      { jersey: 79, name: 'Chip Chapman', team: 'Outlaws', gp: 5, goals: 7, assists: 5, points: 12, penalties: 1, pim: 2 },
      { jersey: 18, name: 'Ryan Rafferty', team: 'Pups LC', gp: 7, goals: 5, assists: 7, points: 12, penalties: 3, pim: 6 },
      { jersey: 59, name: 'Scott MacMillan', team: 'Revolution', gp: 6, goals: 8, assists: 3, points: 11, penalties: 0, pim: 0 },
      { jersey: 27, name: 'Traeger Hogarth', team: 'Thunder', gp: 5, goals: 7, assists: 4, points: 11, penalties: 2, pim: 4 },
      { jersey: 6, name: 'Andrew Bailey', team: 'Revolution', gp: 5, goals: 7, assists: 3, points: 10, penalties: 0, pim: 0 },
      { jersey: 96, name: 'Andrew Streilein', team: 'Pups LC', gp: 4, goals: 7, assists: 3, points: 10, penalties: 1, pim: 2 },
      { jersey: 88, name: 'Michael Buono', team: 'Thunder', gp: 6, goals: 7, assists: 2, points: 9, penalties: 2, pim: 4 },
      { jersey: 22, name: 'Joe Stainer', team: 'Outlaws', gp: 5, goals: 3, assists: 6, points: 9, penalties: 0, pim: 0 },
      { jersey: 44, name: 'Jeffrey Vetter', team: 'Revolution', gp: 3, goals: 7, assists: 1, points: 8, penalties: 0, pim: 0 },
      { jersey: 23, name: 'Cale Stielau', team: 'More Dudes LC', gp: 4, goals: 5, assists: 3, points: 8, penalties: 0, pim: 0 },
      { jersey: 10, name: 'Sam Mutz', team: 'More Dudes LC', gp: 6, goals: 5, assists: 3, points: 8, penalties: 1, pim: 2 },
      { jersey: 22, name: 'Tyler Kostack', team: 'Pups LC', gp: 6, goals: 5, assists: 3, points: 8, penalties: 1, pim: 2 },
      { jersey: 13, name: 'Robert McClure', team: 'More Dudes LC', gp: 5, goals: 7, assists: 0, points: 7, penalties: 0, pim: 0 },
      { jersey: 22, name: 'Deglan Hogarth', team: 'Thunder', gp: 7, goals: 6, assists: 1, points: 7, penalties: 4, pim: 8 },
      { jersey: 43, name: 'Sean Quinn, Jr', team: 'Pups LC', gp: 5, goals: 6, assists: 1, points: 7, penalties: 0, pim: 0 },
      { jersey: 91, name: 'Jason Smaron', team: 'Edge', gp: 5, goals: 4, assists: 3, points: 7, penalties: 0, pim: 0 },
      { jersey: 21, name: 'Ryan Mackey', team: 'Beer Wolves', gp: 6, goals: 4, assists: 3, points: 7, penalties: 2, pim: 4 },
      { jersey: 88, name: 'Caleb Oswari', team: 'Pups LC', gp: 5, goals: 3, assists: 4, points: 7, penalties: 2, pim: 4 },
      { jersey: 7, name: 'Brian Andrews', team: 'Edge', gp: 5, goals: 4, assists: 2, points: 6, penalties: 1, pim: 2 },
      { jersey: 29, name: 'Kinori Rosnow', team: 'Outlaws', gp: 4, goals: 4, assists: 2, points: 6, penalties: 0, pim: 0 },
      { jersey: 2, name: 'Luke Okupski', team: 'Edge', gp: 3, goals: 3, assists: 3, points: 6, penalties: 0, pim: 0 },
      { jersey: 16, name: 'Chris Lasprogata', team: 'Beer Wolves', gp: 4, goals: 4, assists: 1, points: 5, penalties: 3, pim: 6 },
      { jersey: 18, name: 'Gabriel Bonner', team: 'Beer Wolves', gp: 3, goals: 3, assists: 2, points: 5, penalties: 1, pim: 2 },
      { jersey: 19, name: 'Alec Fleming', team: 'Revolution', gp: 3, goals: 2, assists: 3, points: 5, penalties: 0, pim: 0 },
      { jersey: 55, name: 'Joe Walton', team: 'Revolution', gp: 3, goals: 4, assists: 0, points: 4, penalties: 1, pim: 5 },
      { jersey: 31, name: 'Caiden Hawlk', team: 'Outlaws', gp: 4, goals: 3, assists: 1, points: 4, penalties: 0, pim: 0 },
      { jersey: 0, name: 'George Grippo', team: 'Pups LC', gp: 5, goals: 3, assists: 1, points: 4, penalties: 2, pim: 4 },
      { jersey: 67, name: 'Jude Walsh', team: 'Edge', gp: 4, goals: 2, assists: 2, points: 4, penalties: 1, pim: 2 },
      { jersey: 19, name: 'Ben Minardi', team: 'More Dudes LC', gp: 4, goals: 1, assists: 3, points: 4, penalties: 0, pim: 0 },
      { jersey: 30, name: 'Sam Beamer', team: 'More Dudes LC', gp: 4, goals: 1, assists: 3, points: 4, penalties: 1, pim: 2 },
      { jersey: 8, name: 'Andrew Butkus', team: 'Revolution', gp: 3, goals: 0, assists: 4, points: 4, penalties: 0, pim: 0 },
      { jersey: 8, name: 'Frank Haney', team: 'Beer Wolves', gp: 3, goals: 2, assists: 1, points: 3, penalties: 1, pim: 2 },
      { jersey: 35, name: 'Tyler Foulke', team: 'Revolution', gp: 5, goals: 2, assists: 1, points: 3, penalties: 3, pim: 9 },
      { jersey: 22, name: 'Luke Fiorillo', team: 'Beer Wolves', gp: 3, goals: 1, assists: 2, points: 3, penalties: 2, pim: 4 },
      { jersey: 77, name: 'Matt Kruszewski', team: 'Outlaws', gp: 5, goals: 1, assists: 2, points: 3, penalties: 4, pim: 8 },
      { jersey: 30, name: 'Sid Johansen', team: 'Revolution', gp: 3, goals: 0, assists: 3, points: 3, penalties: 0, pim: 0 },
      { jersey: 92, name: 'Ricky Amorim', team: 'Beer Wolves', gp: 2, goals: 2, assists: 0, points: 2, penalties: 0, pim: 0 },
      { jersey: 55, name: 'Chris Lawrence', team: 'Edge', gp: 4, goals: 0, assists: 1, points: 1, penalties: 3, pim: 6 },
      { jersey: 41, name: 'Jason Jones', team: 'Beer Wolves', gp: 3, goals: 0, assists: 0, points: 0, penalties: 4, pim: 6 },
    ],
    goalies: [
      { jersey: 4, name: 'Matt Kuhn', team: 'More Dudes LC', gp: 6, min: 226, ga: 29, gaa: 6.42 },
      { jersey: 30, name: 'Alec Rubman', team: 'Thunder', gp: 7, min: 211, ga: 29, gaa: 6.87 },
      { jersey: 6, name: 'Billy Houser', team: 'More Dudes LC', gp: 5, min: 154, ga: 23, gaa: 7.47 },
      { jersey: 29, name: 'Conor Atkinson', team: 'Thunder', gp: 7, min: 239, ga: 38, gaa: 7.95 },
      { jersey: 28, name: 'Blake Beale', team: 'Pups LC', gp: 7, min: 160, ga: 26, gaa: 8.13 },
      { jersey: 2, name: 'Chase  Beale', team: 'Pups LC', gp: 7, min: 172, ga: 30, gaa: 8.72 },
      { jersey: 19, name: 'Victoria Sloan', team: 'Pups LC', gp: 8, min: 109, ga: 20, gaa: 9.17 },
      { jersey: 69, name: 'Bennett Mileto', team: 'Outlaws', gp: 8, min: 231, ga: 46, gaa: 9.96 },
      { jersey: 30, name: 'Sid Johansen', team: 'Revolution', gp: 10, min: 447, ga: 100, gaa: 11.19 },
      { jersey: 0, name: 'Bryce Kash', team: 'Outlaws', gp: 9, min: 219, ga: 49, gaa: 11.19 },
      { jersey: 0, name: 'Toby Feddor', team: 'Beer Wolves', gp: 6, min: 212, ga: 53, gaa: 12.50 },
      { jersey: 99, name: 'Joshua Hammer', team: 'Beer Wolves', gp: 6, min: 185, ga: 47, gaa: 12.70 },
      { jersey: 38, name: 'Eric Young', team: 'Edge', gp: 7, min: 127, ga: 33, gaa: 12.99 },
      { jersey: 17, name: "Tom O'Hagan", team: 'Edge', gp: 10, min: 313, ga: 83, gaa: 13.26 },
    ],
    rosters: {
      'Beer Wolves': [
        { name: 'Ricky Amorim', jersey: '92', position: '', notes: '' },
        { name: 'Gabriel Bonner', jersey: '18', position: '', notes: '' },
        { name: 'Liam Burns', jersey: '', position: '', notes: '' },
        { name: 'Ryan Carrthers', jersey: '97', position: '', notes: '' },
        { name: 'Timothy Clark', jersey: '2', position: '', notes: '' },
        { name: 'Roman Decenzo', jersey: '13', position: '', notes: '' },
        { name: 'Mackenzie Ensley', jersey: '53', position: '', notes: '' },
        { name: 'Toby Feddor', jersey: '00', position: 'Goalie', notes: '' },
        { name: 'Luke Fiorillo', jersey: '', position: '', notes: '' },
        { name: 'Rob Foster', jersey: '91', position: '', notes: '' },
        { name: 'Joshua Hammer', jersey: '99', position: 'Goalie', notes: '' },
        { name: 'Frank Haney', jersey: '8', position: '', notes: '' },
        { name: 'Jason Jones', jersey: '41', position: '', notes: '' },
        { name: 'Chris Lasprogata', jersey: '16', position: '', notes: '' },
        { name: 'Robert Lowman', jersey: '40', position: '', notes: '' },
        { name: 'Ryan Mackey', jersey: '21', position: '', notes: '' },
        { name: 'Luke Mingioni', jersey: '9', position: '', notes: '' },
        { name: 'William Murdock', jersey: '12', position: '', notes: '' },
        { name: 'Ryan Santo Domingo', jersey: '96', position: '', notes: '' },
        { name: 'Anthony Stranix', jersey: '42', position: '', notes: '' },
        { name: 'Michael Wadley', jersey: '', position: '', notes: '' },
        { name: 'Nate Winters', jersey: '76', position: '', notes: '' },
      ],
      Edge: [
        { name: 'Dave Anderson', jersey: '14', position: '', notes: '' },
        { name: 'Brian Andrews', jersey: '7', position: '', notes: 'Asst' },
        { name: 'George Balascak', jersey: '41', position: '', notes: '' },
        { name: 'Dominic Burphy', jersey: '47', position: '', notes: '' },
        { name: 'Chris Calhoun', jersey: '12', position: '', notes: '' },
        { name: 'Jheramiah Dameus', jersey: '9', position: '', notes: '' },
        { name: 'Julian Definis', jersey: '51', position: '', notes: '' },
        { name: 'Julian Freedman', jersey: '81', position: '', notes: '' },
        { name: 'Pat Gillespie', jersey: '19', position: '', notes: '' },
        { name: 'Jack Glemser', jersey: '4', position: '', notes: '' },
        { name: 'Joe Hagedorn', jersey: '15', position: '', notes: '' },
        { name: 'Spencer Homan', jersey: '87', position: '', notes: '' },
        { name: 'Chris Lawrence', jersey: '55', position: '', notes: '' },
        { name: 'Tanner Mearns', jersey: '28', position: '', notes: '' },
        { name: 'Richard Nelson', jersey: '39', position: '', notes: '' },
        { name: "Matt O'Brien", jersey: '29', position: '', notes: 'Capt' },
        { name: "Tom O'Hagan", jersey: '17', position: 'Goalie', notes: '' },
        { name: 'Luke Okupski', jersey: '2', position: '', notes: '' },
        { name: 'Bailey Orehosky', jersey: '9', position: '', notes: '' },
        { name: 'Michael Plastino', jersey: '19', position: '', notes: '' },
        { name: 'Max Pulcini', jersey: '43', position: '', notes: 'Asst' },
        { name: 'Curtis Reinard', jersey: '5', position: '', notes: '' },
        { name: 'Jason Smaron', jersey: '91', position: '', notes: '' },
        { name: 'Jude Walsh', jersey: '67', position: '', notes: '' },
        { name: 'Sean Walsh', jersey: '16', position: '', notes: '' },
        { name: 'Eric Young', jersey: '38', position: 'Goalie', notes: '' },
      ],
      'More Dudes LC': [
        { name: 'Sam Beamer', jersey: '30', position: '', notes: '' },
        { name: 'Murph Butler', jersey: '17', position: '', notes: '' },
        { name: 'John Creaney', jersey: '47', position: '', notes: '' },
        { name: 'Cristian Davis', jersey: '50', position: '', notes: '' },
        { name: 'Noah Frantz', jersey: '7', position: '', notes: '' },
        { name: 'Rob Hefron', jersey: '77', position: '', notes: '' },
        { name: 'Dalton Hofmann', jersey: '55', position: '', notes: '' },
        { name: 'Billy Houser', jersey: '6', position: 'Goalie', notes: '' },
        { name: 'Ethan Krauss', jersey: '3', position: '', notes: '' },
        { name: 'Matt Kuhn', jersey: '4', position: 'Goalie', notes: '' },
        { name: 'Brett Lundberg', jersey: '42', position: '', notes: '' },
        { name: 'Tom McAneney', jersey: '71', position: '', notes: '' },
        { name: 'Robert McClure', jersey: '13', position: '', notes: '' },
        { name: 'Jonathan Miller', jersey: '5', position: '', notes: '' },
        { name: 'Ben Minardi', jersey: '19', position: '', notes: '' },
        { name: 'Sam Mutz', jersey: '10', position: '', notes: '' },
        { name: 'Wade Mutz', jersey: '24', position: '', notes: '' },
        { name: 'Erik Ojert', jersey: '67', position: '', notes: '' },
        { name: 'Tyler Rotkowitz', jersey: '9', position: '', notes: '' },
        { name: 'Guile Schltzkie', jersey: '26', position: '', notes: '' },
        { name: 'Evan Scott', jersey: '92', position: '', notes: '' },
        { name: 'Cale Stielau', jersey: '23', position: '', notes: '' },
        { name: 'Jake Townsend', jersey: '31', position: '', notes: '' },
        { name: 'Greg Wheaton', jersey: '88', position: '', notes: '' },
        { name: 'Adam Yee', jersey: '11', position: '', notes: '' },
      ],
      Outlaws: [
        { name: 'Niall Bailey', jersey: '56', position: '', notes: '' },
        { name: 'Brian Beatson', jersey: '92', position: '', notes: '' },
        { name: 'Ian Bittenbender', jersey: '6', position: '', notes: '' },
        { name: 'Brandon Cerone', jersey: '1', position: '', notes: '' },
        { name: 'Chip Chapman', jersey: '79', position: '', notes: '' },
        { name: 'George Downey', jersey: '96', position: '', notes: '' },
        { name: 'Jovan Estrada', jersey: '25', position: '', notes: '' },
        { name: 'Jeff Gonzales84', jersey: '66', position: '', notes: '' },
        { name: 'Brady Hawlk', jersey: '9', position: '', notes: '' },
        { name: 'Caiden Hawlk', jersey: '31', position: '', notes: '' },
        { name: 'Kees Holterman', jersey: '63', position: '', notes: '' },
        { name: 'Bryce Kash', jersey: '0', position: 'Goalie', notes: '' },
        { name: 'Matt Kruszewski', jersey: '77', position: '', notes: '' },
        { name: 'Adam Kulp', jersey: '20', position: '', notes: '' },
        { name: 'William Mahon', jersey: '19', position: '', notes: '' },
        { name: 'Aedan McKenna', jersey: '87', position: '', notes: '' },
        { name: 'Philip Melecio', jersey: '55', position: '', notes: '' },
        { name: 'Bennett Mileto', jersey: '69', position: 'Goalie', notes: '' },
        { name: 'Camdon Pierce', jersey: '3', position: '', notes: '' },
        { name: 'Dylan Pool', jersey: '18', position: '', notes: '' },
        { name: 'Dylan Portnoy', jersey: '16', position: '', notes: '' },
        { name: 'Dan Recine', jersey: '49', position: '', notes: '' },
        { name: 'Kinori Rosnow', jersey: '29', position: '', notes: '' },
        { name: 'Joe Stainer', jersey: '22', position: '', notes: '' },
        { name: 'Brian Sullivan', jersey: '88', position: '', notes: '' },
        { name: 'Evan Swiker', jersey: '15', position: '', notes: '' },
      
        { name: 'Jeff Gonzales', jersey: '66', position: '', notes: '' },],
      'Pups LC': [
        { name: 'Logan Amaya', jersey: '8', position: '', notes: '' },
        { name: 'Logan Barlok', jersey: '91', position: '', notes: '' },
        { name: 'Blake Beale', jersey: '28', position: '', notes: '' },
        { name: 'Brent Beale', jersey: '26', position: '', notes: '' },
        { name: 'Chase Beale', jersey: '2', position: 'Goalie', notes: '' },
        { name: 'Colin Bosak', jersey: '11', position: '', notes: '' },
        { name: 'Reece Childs', jersey: '6', position: '', notes: '' },
        { name: 'Nick Fox', jersey: '7', position: '', notes: '' },
        { name: 'George Grippo', jersey: '00', position: '', notes: '' },
        { name: 'Soloman Hess', jersey: '77', position: '', notes: '' },
        { name: 'Tyler Kostack', jersey: '22', position: '', notes: '' },
        { name: 'Chris Lieze-Hammel', jersey: '34', position: '', notes: '' },
        { name: 'James Lindsay', jersey: '24', position: '', notes: '' },
        { name: 'Caleb Oswari', jersey: '88', position: '', notes: '' },
        { name: 'Ryan Quinn', jersey: '14', position: '', notes: '' },
        { name: 'Sean Quinn, Jr', jersey: '43', position: '', notes: '' },
        { name: 'Ryan Rafferty', jersey: '18', position: '', notes: '' },
        { name: 'Mattew Rueter', jersey: '45', position: '', notes: '' },
        { name: 'Andrew Sloan', jersey: '86', position: '', notes: '' },
        { name: 'Victoria Sloan', jersey: '19', position: 'Goalie', notes: '' },
        { name: 'Andrew Streilein', jersey: '96', position: '', notes: '' },
        { name: 'Caiden Zadell', jersey: '51', position: '', notes: '' },
      ],
      Revolution: [
        { name: 'Andrew Bailey', jersey: '', position: '', notes: '' },
        { name: 'Andrew Butkus', jersey: '8', position: '', notes: '' },
        { name: 'Nicholas Cost', jersey: '9', position: '', notes: '' },
        { name: 'Jayden Cox', jersey: '10', position: '', notes: '' },
        { name: 'Alec Fleming', jersey: '19', position: '', notes: '' },
        { name: 'Tyler Foulke', jersey: '35', position: '', notes: '' },
        { name: 'Connor Freer', jersey: '2', position: '', notes: '' },
        { name: 'Ricky Gergasko', jersey: '64', position: '', notes: '' },
        { name: 'Jack Gerzabek', jersey: '39', position: '', notes: '' },
        { name: 'Ian Hagan', jersey: '21', position: '', notes: '' },
        { name: 'Sabastian Hamilton', jersey: '22', position: '', notes: '' },
        { name: 'Scott Jackson', jersey: '88', position: '', notes: '' },
        { name: 'Sid Johansen', jersey: '30', position: 'Goalie', notes: '' },
        { name: 'Scott MacMillan', jersey: '59', position: '', notes: '' },
        { name: 'Sean McMaster', jersey: '27', position: '', notes: '' },
        { name: 'Brandon Reese', jersey: '11', position: '', notes: '' },
        { name: 'James Reilly', jersey: '77', position: '', notes: '' },
        { name: 'Andrew Ruiz', jersey: '17', position: '', notes: '' },
        { name: 'Russ Taranto', jersey: '34', position: '', notes: '' },
        { name: 'Jeffrey Vetter', jersey: '44', position: '', notes: '' },
        { name: 'Dave Voyles', jersey: '49', position: '', notes: '' },
        { name: 'Joe Walton', jersey: '55', position: '', notes: '' },
      ],
      Thunder: [
        { name: 'Conor Atkinson', jersey: '29', position: 'Goalie', notes: '' },
        { name: 'Michael Buono', jersey: '88', position: '', notes: '' },
        { name: 'Michael Carbone', jersey: '41', position: '', notes: '' },
        { name: 'Austin Conner', jersey: '10', position: '', notes: '' },
        { name: 'Brian Dailey', jersey: '61', position: '', notes: 'Capt' },
        { name: 'Jimmy Gabrielsen', jersey: '36', position: '', notes: '' },
        { name: 'Adam Goldner', jersey: '99', position: '', notes: '' },
        { name: 'Jake Hervada', jersey: '1', position: '', notes: '' },
        { name: 'Deglan Hogarth', jersey: '22', position: '', notes: '' },
        { name: 'Traeger Hogarth', jersey: '27', position: '', notes: '' },
        { name: 'Michael Jamieson', jersey: '0', position: '', notes: '' },
        { name: 'Tim Kiel', jersey: '17', position: '', notes: '' },
        { name: 'Joey Klinges', jersey: '4', position: '', notes: 'Asst' },
        { name: 'Matt Klinges', jersey: '91', position: '', notes: '' },
        { name: 'Kellen Korb', jersey: '24', position: '', notes: '' },
        { name: 'Kyle Marr', jersey: '51', position: '', notes: '' },
        { name: 'Seamus McCloskey', jersey: '7', position: '', notes: '' },
        { name: 'Ryan McNulty', jersey: '19', position: '', notes: '' },
        { name: 'Ryan Quan', jersey: '13', position: '', notes: '' },
        { name: 'Conor Resch', jersey: '34', position: '', notes: 'Asst' },
        { name: 'Patrick Resch', jersey: '33', position: '', notes: '' },
        { name: 'Alec Rubman', jersey: '30', position: '', notes: '' },
        { name: 'Pat Smyth', jersey: '71', position: '', notes: '' },
        { name: 'Mike Weaver', jersey: '16', position: '', notes: '' },
      ],
    },
    games: [
      { gameNum: 1, date: '2026-05-18', time: '7:00p', homeTeam: 'More Dudes LC', awayTeam: 'Outlaws', homeScore: 14, awayScore: 5, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 2, date: '2026-05-18', time: '8:00p', homeTeam: 'Pups LC', awayTeam: 'Thunder', homeScore: 8, awayScore: 9, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 3, date: '2026-05-20', time: '7:00p', homeTeam: 'Revolution', awayTeam: 'Outlaws', homeScore: 4, awayScore: 15, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 4, date: '2026-05-20', time: '8:00p', homeTeam: 'Beer Wolves', awayTeam: 'Edge', homeScore: 8, awayScore: 11, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 5, date: '2026-05-27', time: '7:00p', homeTeam: 'Thunder', awayTeam: 'Edge', homeScore: 14, awayScore: 2, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 6, date: '2026-05-27', time: '8:00p', homeTeam: 'Revolution', awayTeam: 'Pups LC', homeScore: 4, awayScore: 17, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 7, date: '2026-06-01', time: '7:00p', homeTeam: 'More Dudes LC', awayTeam: 'Pups LC', homeScore: 5, awayScore: 9, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 8, date: '2026-06-01', time: '8:00p', homeTeam: 'Revolution', awayTeam: 'Thunder', homeScore: 5, awayScore: 12, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 9, date: '2026-06-03', time: '7:00p', homeTeam: 'Beer Wolves', awayTeam: 'Outlaws', homeScore: 5, awayScore: 10, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 10, date: '2026-06-03', time: '8:00p', homeTeam: 'Revolution', awayTeam: 'More Dudes LC', homeScore: 6, awayScore: 14, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 11, date: '2026-06-08', time: '7:00p', homeTeam: 'More Dudes LC', awayTeam: 'Beer Wolves', homeScore: 14, awayScore: 4, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 12, date: '2026-06-08', time: '8:00p', homeTeam: 'Edge', awayTeam: 'Outlaws', homeScore: 10, awayScore: 12, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 13, date: '2026-06-10', time: '7:00p', homeTeam: 'Edge', awayTeam: 'Pups LC', homeScore: 5, awayScore: 14, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 14, date: '2026-06-10', time: '8:00p', homeTeam: 'More Dudes LC', awayTeam: 'Thunder', homeScore: 5, awayScore: 7, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 15, date: '2026-06-15', time: '7:00p', homeTeam: 'Outlaws', awayTeam: 'Thunder', homeScore: 11, awayScore: 12, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 16, date: '2026-06-15', time: '8:00p', homeTeam: 'Pups LC', awayTeam: 'Revolution', homeScore: 8, awayScore: 6, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 17, date: '2026-06-17', time: '7:00p', homeTeam: 'Edge', awayTeam: 'More Dudes LC', homeScore: 10, awayScore: 14, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 18, date: '2026-06-17', time: '8:00p', homeTeam: 'Pups LC', awayTeam: 'Outlaws', homeScore: 12, awayScore: 11, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 19, date: '2026-06-22', time: '7:00p', homeTeam: 'Revolution', awayTeam: 'Beer Wolves', homeScore: 6, awayScore: 4, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 20, date: '2026-06-22', time: '8:00p', homeTeam: 'Pups LC', awayTeam: 'Edge', homeScore: 8, awayScore: 4, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 21, date: '2026-06-24', time: '7:00p', homeTeam: 'Beer Wolves', awayTeam: 'Edge', homeScore: 12, awayScore: 13, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 22, date: '2026-06-24', time: '8:00p', homeTeam: 'Revolution', awayTeam: 'Outlaws', homeScore: 8, awayScore: 11, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 23, date: '2026-06-29', time: '7:00p', homeTeam: 'Thunder', awayTeam: 'Beer Wolves', homeScore: 16, awayScore: 7, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 24, date: '2026-06-29', time: '8:00p', homeTeam: 'Edge', awayTeam: 'More Dudes LC', homeScore: 3, awayScore: 12, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 25, date: '2026-07-01', time: '7:00p', homeTeam: 'Revolution', awayTeam: 'Beer Wolves', homeScore: 4, awayScore: 5, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 26, date: '2026-07-01', time: '8:00p', homeTeam: 'Pups LC', awayTeam: 'Outlaws', homeScore: 9, awayScore: 7, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 27, date: '2026-07-06', time: '7:00p', homeTeam: 'More Dudes LC', awayTeam: 'Revolution', homeScore: 0, awayScore: 0, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 28, date: '2026-07-06', time: '8:00p', homeTeam: 'Outlaws', awayTeam: 'Beer Wolves', homeScore: 0, awayScore: 0, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 29, date: '2026-07-08', time: '7:00p', homeTeam: 'Thunder', awayTeam: 'Edge', homeScore: 14, awayScore: 4, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 30, date: '2026-07-08', time: '8:00p', homeTeam: 'Outlaws', awayTeam: 'More Dudes LC', homeScore: 7, awayScore: 12, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 31, date: '2026-07-13', time: '7:00p', homeTeam: 'Beer Wolves', awayTeam: 'Pups LC', homeScore: 12, awayScore: 7, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 32, date: '2026-07-13', time: '8:00p', homeTeam: 'Revolution', awayTeam: 'Thunder', homeScore: 6, awayScore: 11, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 33, date: '2026-07-15', time: '7:00p', homeTeam: 'Thunder', awayTeam: 'Pups LC', homeScore: 13, awayScore: 12, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 34, date: '2026-07-15', time: '8:00p', homeTeam: 'Beer Wolves', awayTeam: 'More Dudes LC', homeScore: 7, awayScore: 19, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 35, date: '2026-07-20', time: '7:00p', homeTeam: 'Thunder', awayTeam: 'Outlaws', homeScore: 10, awayScore: 7, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 36, date: '2026-07-20', time: '8:00p', homeTeam: 'Revolution', awayTeam: 'Edge', homeScore: 10, awayScore: 3, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 37, date: '2026-07-22', time: '7:00p', homeTeam: 'Pups LC', awayTeam: 'More Dudes LC', homeScore: 4, awayScore: 15, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 38, date: '2026-07-22', time: '8:00p', homeTeam: 'Outlaws', awayTeam: 'Edge', homeScore: 12, awayScore: 6, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 39, date: '2026-07-27', time: '7:00p', homeTeam: 'Thunder', awayTeam: 'Beer Wolves', homeScore: 0, awayScore: 0, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 40, date: '2026-07-27', time: '8:00p', homeTeam: 'Revolution', awayTeam: 'Edge', homeScore: 0, awayScore: 0, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 41, date: '2026-07-29', time: '7:00p', homeTeam: 'Beer Wolves', awayTeam: 'Pups LC', homeScore: 0, awayScore: 0, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 42, date: '2026-07-29', time: '8:00p', homeTeam: 'Thunder', awayTeam: 'More Dudes LC', homeScore: 0, awayScore: 0, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 43, date: '2026-08-05', time: '7:00p', homeTeam: 'TBD', awayTeam: 'TBD', homeScore: 0, awayScore: 0, location: 'Rizzo Rink', isPlayoff: true, note: '' },
      { gameNum: 44, date: '2026-08-05', time: '8:00p', homeTeam: 'TBD', awayTeam: 'TBD', homeScore: 0, awayScore: 0, location: 'Rizzo Rink', isPlayoff: true, note: '' },
      { gameNum: 45, date: '2026-08-10', time: '7:30p', homeTeam: 'TBD', awayTeam: 'TBD', homeScore: 0, awayScore: 0, location: 'Rizzo Rink', isPlayoff: true, note: '' },
    ],
  },
  {
    year: 2025,
    leagueId: 50247,
    label: '2025 (Complete)',
    teams: [
      { id: 339148, name: 'More Dudes', gp: 12, wins: 11, losses: 1, ties: 0, otw: 0, otl: 0, pts: 33, pf: 148, pa: 62, diff: 86, streak: 'W7', color: '#800000' },
      { id: 339150, name: 'Thunder', gp: 12, wins: 9, losses: 3, ties: 0, otw: 0, otl: 1, pts: 28, pf: 115, pa: 72, diff: 43, streak: 'L2', color: '#facc15' },
      { id: 339152, name: 'Beer Wolves', gp: 12, wins: 9, losses: 3, ties: 0, otw: 1, otl: 0, pts: 26, pf: 109, pa: 90, diff: 19, streak: 'W2', color: '#22c55e' },
      { id: 339153, name: 'Black Storm', gp: 12, wins: 7, losses: 5, ties: 0, otw: 0, otl: 0, pts: 21, pf: 115, pa: 89, diff: 26, streak: 'L3', color: '#64748b' },
      { id: 339149, name: 'Outlaws', gp: 12, wins: 4, losses: 8, ties: 0, otw: 0, otl: 0, pts: 12, pf: 99, pa: 107, diff: -8, streak: 'W1', color: '#003087' },
      { id: 339154, name: 'Revolution LC', gp: 12, wins: 2, losses: 10, ties: 0, otw: 0, otl: 0, pts: 6, pf: 67, pa: 117, diff: -50, streak: 'W2', color: '#3b82f6' },
      { id: 339151, name: 'The Edge', gp: 12, wins: 0, losses: 12, ties: 0, otw: 0, otl: 0, pts: 0, pf: 48, pa: 164, diff: -116, streak: 'L12', color: '#ef4444' },
    ],
    players: [
      { jersey: 31, name: 'Carter Begley', team: 'More Dudes', gp: 9, goals: 36, assists: 7, points: 43, penalties: 1, pim: 2 },
      { jersey: 24, name: 'James Lindsay', team: 'Black Storm', gp: 10, goals: 19, assists: 13, points: 32, penalties: 2, pim: 4 },
      { jersey: 13, name: 'Ryan Quan', team: 'Thunder', gp: 9, goals: 19, assists: 10, points: 29, penalties: 1, pim: 2 },
      { jersey: 18, name: 'Connor Mann', team: 'Beer Wolves', gp: 10, goals: 20, assists: 8, points: 28, penalties: 5, pim: 8 },
      { jersey: 76, name: 'Nathaniel Winters', team: 'Beer Wolves', gp: 10, goals: 19, assists: 8, points: 27, penalties: 0, pim: 0 },
      { jersey: 22, name: 'Joe Stainer', team: 'Outlaws', gp: 11, goals: 11, assists: 15, points: 26, penalties: 5, pim: 10 },
      { jersey: 17, name: 'Murphy Butler', team: 'More Dudes', gp: 9, goals: 14, assists: 11, points: 25, penalties: 3, pim: 6 },
      { jersey: 55, name: 'Dalton Hofmann', team: 'More Dudes', gp: 10, goals: 12, assists: 7, points: 19, penalties: 3, pim: 6 },
      { jersey: 55, name: 'Phillip Melecio', team: 'Outlaws', gp: 10, goals: 16, assists: 3, points: 19, penalties: 3, pim: 6 },
      { jersey: 16, name: 'Dylan Portnoy', team: 'Outlaws', gp: 10, goals: 10, assists: 5, points: 15, penalties: 1, pim: 2 },
    ],
    goalies: [
      { jersey: 6, name: 'Billy Houser', team: 'More Dudes', gp: 11, min: 480, ga: 52, gaa: 5.42 },
      { jersey: 28, name: 'Blake Beale', team: 'Black Storm', gp: 9, min: 249, ga: 38, gaa: 7.63 },
      { jersey: 30, name: 'Alec Rubman', team: 'Thunder', gp: 7, min: 227, ga: 37, gaa: 8.15 },
      { jersey: 43, name: 'Matt Kuhn', team: 'Outlaws', gp: 8, min: 214, ga: 36, gaa: 8.41 },
      { jersey: 86, name: 'Andrew Sloan', team: 'Black Storm', gp: 10, min: 231, ga: 42, gaa: 9.09 },
      { jersey: 0, name: 'Toby Feddor', team: 'Beer Wolves', gp: 8, min: 302, ga: 57, gaa: 9.44 },
      { jersey: 30, name: 'Sid Johansen', team: 'Revolution LC', gp: 11, min: 462, ga: 90, gaa: 9.74 },
      { jersey: 0, name: 'Kiernan Clark', team: 'Outlaws', gp: 11, min: 325, ga: 64, gaa: 9.85 },
      { jersey: 38, name: 'Eric Young', team: 'The Edge', gp: 11, min: 269, ga: 81, gaa: 15.06 },
      { jersey: 48, name: 'Victoria Sloan', team: 'The Edge', gp: 9, min: 202, ga: 61, gaa: 15.10 },
    ],
    rosters: {},
    games: [
      { gameNum: 1, date: '2025-05-19', time: '7:00p', homeTeam: 'Outlaws', awayTeam: 'More Dudes', homeScore: 2, awayScore: 9, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 2, date: '2025-05-19', time: '7:50p', homeTeam: 'Thunder', awayTeam: 'Black Storm', homeScore: 11, awayScore: 7, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 3, date: '2025-05-21', time: '7:00p', homeTeam: 'Revolution LC', awayTeam: 'Outlaws', homeScore: 4, awayScore: 8, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 4, date: '2025-05-21', time: '7:50p', homeTeam: 'The Edge', awayTeam: 'Beer Wolves', homeScore: 3, awayScore: 17, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 5, date: '2025-08-04', time: '7:00p', homeTeam: 'Beer Wolves', awayTeam: 'Thunder', homeScore: 12, awayScore: 11, location: 'Rizzo Rink', isPlayoff: false, note: 'Overtime' },
      { gameNum: 6, date: '2025-08-04', time: '7:50p', homeTeam: 'More Dudes', awayTeam: 'The Edge', homeScore: 22, awayScore: 3, location: 'Rizzo Rink', isPlayoff: false, note: 'Rainout' },
      { gameNum: 7, date: '2025-06-02', time: '7:00p', homeTeam: 'The Edge', awayTeam: 'Thunder', homeScore: 4, awayScore: 21, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 8, date: '2025-06-02', time: '7:50p', homeTeam: 'Black Storm', awayTeam: 'Revolution LC', homeScore: 5, awayScore: 3, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 9, date: '2025-06-04', time: '7:00p', homeTeam: 'Outlaws', awayTeam: 'Beer Wolves', homeScore: 8, awayScore: 9, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 10, date: '2025-06-04', time: '7:50p', homeTeam: 'More Dudes', awayTeam: 'Revolution LC', homeScore: 11, awayScore: 5, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 11, date: '2025-06-09', time: '7:00p', homeTeam: 'Black Storm', awayTeam: 'More Dudes', homeScore: 5, awayScore: 9, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 12, date: '2025-06-09', time: '7:50p', homeTeam: 'Thunder', awayTeam: 'Revolution LC', homeScore: 11, awayScore: 6, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 13, date: '2025-06-11', time: '7:00p', homeTeam: 'Beer Wolves', awayTeam: 'More Dudes', homeScore: 8, awayScore: 13, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 14, date: '2025-06-11', time: '7:50p', homeTeam: 'Outlaws', awayTeam: 'The Edge', homeScore: 16, awayScore: 3, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 15, date: '2025-06-16', time: '7:00p', homeTeam: 'Black Storm', awayTeam: 'The Edge', homeScore: 13, awayScore: 2, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 16, date: '2025-06-16', time: '7:50p', homeTeam: 'Thunder', awayTeam: 'More Dudes', homeScore: 10, awayScore: 8, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 17, date: '2025-06-18', time: '7:00p', homeTeam: 'Thunder', awayTeam: 'Outlaws', homeScore: 12, awayScore: 6, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 18, date: '2025-06-18', time: '7:50p', homeTeam: 'Revolution LC', awayTeam: 'Black Storm', homeScore: 3, awayScore: 11, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 19, date: '2025-06-23', time: '7:00p', homeTeam: 'More Dudes', awayTeam: 'The Edge', homeScore: 7, awayScore: 4, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 20, date: '2025-06-23', time: '7:50p', homeTeam: 'Outlaws', awayTeam: 'Black Storm', homeScore: 8, awayScore: 11, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 21, date: '2025-06-25', time: '7:00p', homeTeam: 'Beer Wolves', awayTeam: 'Revolution LC', homeScore: 9, awayScore: 6, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 22, date: '2025-06-25', time: '7:50p', homeTeam: 'Black Storm', awayTeam: 'The Edge', homeScore: 18, awayScore: 2, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 23, date: '2025-06-30', time: '7:00p', homeTeam: 'Outlaws', awayTeam: 'Revolution LC', homeScore: 15, awayScore: 4, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 24, date: '2025-06-30', time: '7:50p', homeTeam: 'The Edge', awayTeam: 'Beer Wolves', homeScore: 7, awayScore: 12, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 25, date: '2025-07-25', time: '7:00p', homeTeam: 'Black Storm', awayTeam: 'Thunder', homeScore: 4, awayScore: 7, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 26, date: '2025-07-25', time: '7:50p', homeTeam: 'More Dudes', awayTeam: 'Beer Wolves', homeScore: 8, awayScore: 3, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 27, date: '2025-08-01', time: '7:00p', homeTeam: 'The Edge', awayTeam: 'Revolution LC', homeScore: 7, awayScore: 11, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 28, date: '2025-08-01', time: '7:50p', homeTeam: 'Thunder', awayTeam: 'Beer Wolves', homeScore: 0, awayScore: 1, location: 'Rizzo Rink', isPlayoff: false, note: 'Forfeit' },
      { gameNum: 29, date: '2025-07-09', time: '7:00p', homeTeam: 'Beer Wolves', awayTeam: 'Revolution LC', homeScore: 10, awayScore: 4, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 30, date: '2025-07-09', time: '7:50p', homeTeam: 'Outlaws', awayTeam: 'Black Storm', homeScore: 8, awayScore: 13, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 31, date: '2025-07-14', time: '7:00p', homeTeam: 'Black Storm', awayTeam: 'Beer Wolves', homeScore: 17, awayScore: 9, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 32, date: '2025-07-14', time: '7:50p', homeTeam: 'More Dudes', awayTeam: 'Thunder', homeScore: 10, awayScore: 8, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 33, date: '2025-07-16', time: '7:00p', homeTeam: 'Revolution LC', awayTeam: 'More Dudes', homeScore: 5, awayScore: 18, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 34, date: '2025-07-16', time: '7:50p', homeTeam: 'Beer Wolves', awayTeam: 'Outlaws', homeScore: 9, awayScore: 6, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 35, date: '2025-07-21', time: '7:00p', homeTeam: 'Black Storm', awayTeam: 'Beer Wolves', homeScore: 7, awayScore: 10, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 36, date: '2025-07-21', time: '7:50p', homeTeam: 'Thunder', awayTeam: 'Revolution LC', homeScore: 8, awayScore: 5, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 37, date: '2025-07-23', time: '7:00p', homeTeam: 'The Edge', awayTeam: 'Thunder', homeScore: 1, awayScore: 7, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 38, date: '2025-07-23', time: '7:50p', homeTeam: 'More Dudes', awayTeam: 'Outlaws', homeScore: 16, awayScore: 5, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 39, date: '2025-07-28', time: '7:00p', homeTeam: 'Outlaws', awayTeam: 'Thunder', homeScore: 8, awayScore: 9, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 40, date: '2025-07-28', time: '7:50p', homeTeam: 'The Edge', awayTeam: 'Revolution LC', homeScore: 4, awayScore: 11, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 41, date: '2025-07-30', time: '7:00p', homeTeam: 'More Dudes', awayTeam: 'Black Storm', homeScore: 17, awayScore: 4, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 42, date: '2025-07-30', time: '7:50p', homeTeam: 'The Edge', awayTeam: 'Outlaws', homeScore: 8, awayScore: 9, location: 'Rizzo Rink', isPlayoff: false, note: '' },
      { gameNum: 43, date: '2025-08-06', time: '7:00p', homeTeam: 'More Dudes', awayTeam: 'Black Storm', homeScore: 12, awayScore: 9, location: 'Rizzo Rink', isPlayoff: true, note: '' },
      { gameNum: 44, date: '2025-08-06', time: '7:50p', homeTeam: 'Thunder', awayTeam: 'Beer Wolves', homeScore: 12, awayScore: 8, location: 'Rizzo Rink', isPlayoff: true, note: 'ShootOut' },
      { gameNum: 45, date: '2025-08-11', time: '7:30p', homeTeam: 'More Dudes', awayTeam: 'Thunder', homeScore: 7, awayScore: 10, location: 'Rizzo Rink', isPlayoff: true, note: '' },
    ],
  },
];

export const PBLA_SEASONS = SEASONS;
export const PBLA_DEFAULT_SEASON = 2026;

export function getPblaSeason(year: number): PblaSeason {
  return SEASONS.find((season) => season.year === year) ?? SEASONS[0]!;
}

/**
 * YouTube stream video IDs keyed by game date (YYYY-MM-DD).
 * Each date has ONE stream covering both games played that night.
 * Source: https://www.youtube.com/@PBLA_Official/streams
 * Auto-synced by syncPblaVideos.ts (runs Tue/Thu via sync-pbla.yml).
 * Published date is always day-after-game; dates here are actual game dates
 * parsed from the video title.
 */
export const PBLA_VIDEOS: Record<string, string> = {
  // 2026 season - auto-synced from @PBLA_Official YouTube
  '2026-05-18': 'rE0TzPfV5SY',
  '2026-05-20': 'hMd-kLZXl7o',
  '2026-05-27': 't09kMS7NBE0',
  '2026-06-01': 'WEoPQhKx6XI',
  '2026-06-03': 'RO5kM20BRTc',
  '2026-06-08': 'WIKY9Ed0XBA',
  '2026-06-10': 'gXxr2XrkuY8',
  '2026-06-15': 'D-v90bDNzLY',
  '2026-06-17': 'PN00-Xy3RiY',
  '2026-06-22': 'MHCdYwUqOJo',
  '2026-06-24': 'v8STpVJKpJU',
  '2026-06-29': 'uiyvWIAhv78',
  '2026-07-01': '5m3Q5WXyqPA',
  '2026-07-08': 'reyt2H_vmc8',
  '2026-07-13': 'TcxDL4dmq1E',
  '2026-07-15': 'Qdu1-HCk2Wk',
  '2026-07-20': 'Qdu1-HCk2Wk',
};

/** Get the YouTube video ID for a game date, if available */
export function getGameVideoId(date: string): string | null {
  return PBLA_VIDEOS[date] ?? null;
}

/** Get all games for a specific team in a season */
export function getTeamGames(teamName: string, season: PblaSeason): PblaGame[] {
  return season.games.filter(
    (g) => g.homeTeam === teamName || g.awayTeam === teamName,
  );
}
